<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Footer</title>
</head>
<body>
<style>
    .maindiv{
        display : flex;
    }
    .maindiv h3 {
        color : black;
        font-size : 20px;
        background-color: beige;
        padding : 10px;
        border-radius: 10px;
    }
</style>
<div class="maindiv">
    <h3>© 2023 php web project by mohit rathod, all rights reserved</h3>
</div>
</body>
</html>