<div>
	<?php 

	$this->getMessage()->getSession()->start();
	$messages = $this->getMessage()->getMessages();

	if ($messages) {
		foreach($messages as $type => $message )
		{
			?>
			<p class="<?php echo $type; ?>"><?php echo $message; ?></p>
			<?php
		}
	}
	$this->getMessage()->clearMessages();
	$this->getMessage()->getSession()->destroy();

	?>
	<style type="text/css">
		.success{
			color: green;
			font-size: 20px;
			text-align: center;
		}
		.failure{
			color: red;
			font-size: 20px;
			text-align: center;
		}
		.notice{
			color: orange;
			font-size: 20px;
			text-align: center;
		}
	</style>
</div>