<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="skin/css/add.css?<?php echo time(); ?>" />
    <title>Insert Data</title>
</head> 
<body>
    <!-- <form action="index.php?c=product&a=insert" method="post"> -->
    <form action="<?php echo $this->getUrlObj()->getUrl('product', 'insert'); ?>" method="post">
        <div class="mainadd">
            <div class="eachdiv">
                <label>NAME</label>
                <input type="text" name="product[name]" placeholder="enter your name"  />
            </div>
                
            <div class="eachdiv">  
                <label>SKU</label>
                <input type="number" name="product[sku]" placeholder="enter sku"  />
            </div>  

            <div class="eachdiv">
                <label>COST</label>
                <input type="number" name="product[cost]" placeholder="enter cost"  />
            </div>
                
            <div class="eachdiv">
                <label>PRICE</label>
                <input type="number" name="product[price]" placeholder="enter price"  />
            </div>
                
            <div class="eachdiv">
                <label>QUANTITY</label>
                <input type="number" name="product[quantity]" placeholder="enter quantity"  />
            </div>

            <div class="eachdiv">
                <label>DESCRIPTION</label>
                <textarea name="product[description]" id="" cols="6" rows="4" placeholder="enter description" ></textarea>
            </div>
                
            <div class="eachdiv">
                <label>COLOR</label>
                <select name="product[color]" >
                    <option>select</option>
                    <option value="red">Red</option>
                    <option value="blue">Blue</option>
                </select>
            </div>

            <div class="eachdiv">
                <label>STATUS</label>
                <select name="product[status]" >
                    <option>select</option>
                    <option value="active">active</option>
                    <option value="inactive">inactive</option>
                </select>
            </div>

            <div class="eachdiv">
                <label>MATERIAL</label>
                <select name="product[material]" >
                    <option>select</option>
                    <option value="glass">Glass</option>
                    <option value="metal">Metal</option>
                    <option value="plastic">Plastic</option>
                </select>
            </div>

            <div class="eachdiv">
                <input type="submit" class="submitbutton" />
                <a href="<?php echo $this->getUrlObj()->getUrl('product', 'grid'); ?>">CANCEL</a>
                <!-- <a href="index.php?c=product&a=grid">CANCEL</a> -->
            </div>
        </div>
    </form>
</body>
</html>