<?php
$products = $this->getCollection()->getData();
?>
<div class="maindiv">
        <div class="subdiv">
            <!-- header -->
            <div class="headerr">
            </div>
            <!-- head -->
            <div class="headd">
                <span>Products</span>
                <a href="<?php echo Ccc::getModel("Core_Url")->getUrl('product' , 'add') ?>">Add product</a>
            </div>
        </div>  
        
        <!-- data table -->
        <div class="table">
            <table border="1px" border-collapse= "collapse">
                <tr>
                    <th>product_id</th>
                    <th>name</th>
                    <th>sku</th>
                    <th>cost</th>
                    <th>price</th>
                    <th>quantity</th>
                    <th>description</th>
                    <th>color</th>
                    <th>status</th>
                    <th>material</th>
                    <th>Created At</th>
                    <th>Updated At</th>
                    <th>MEDIA</th>
                    <th>EDIT</th>
                    <th>DELETE</th>
                </tr>
                <?php if(!$products): ?>
                    <tr><td colspan="8">no data available</td></tr>
                <?php else: ?>

                    <?php
                    foreach($products as $product){
                    ?>
                <tr>
                        <td><?php echo $product->product_id ?></td>
                        <td><?php echo $product->name ?></td>
                        <td><?php echo $product->sku ?></td>
                        <td><?php echo $product->cost ?></td>
                        <td><?php echo $product->price ?></td>
                        <td><?php echo $product->quantity ?></td>
                        <td><?php echo $product->description ?></td>
                        <td><?php echo $product->color ?></td>
                        <td><?php echo $product->status ?></td>
                        <td><?php echo $product->material ?></td>
                        <td><?php echo $product->created_at ?></td>
                        <td><?php echo $product->updated_at ?></td>
                        <td><a href="<?php echo Ccc::getModel("Core_Url")->getUrl('product_media','grid', ['id' => $product->product_id]) ?>">MEDIA</a></td>

                        <td><a href="<?php echo Ccc::getModel("Core_Url")->getUrl('product', 'edit', ['id' => $product->product_id]) ?>">EDIT</a></td>
                       
                        <td><a href="<?php echo Ccc::getModel("Core_Url")->getUrl('product', 'delete', ['id' => $product->product_id]) ?>">DELETE</a></td>
                </tr>

                    <?php
                    }
                    ?>
                <?php endif; ?>
            </table>
        </div>

        <div>
        </div>
    </div>
</body>
</html>