<?php
$shippings = $this->getShipping();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="skin/css/edit.css?<?php echo time(); ?>">
    <title>Edit SHIPPING</title>
</head>
<body>
<form action="index.php?c=shipping&a=update&id=<?php echo $shippings['shipping_method_id'] ?>" method="post">
    <div class="mainadd">

        <div class="eachdiv">
            <label>EDIT NAME</label>
            <input type="text" name="shipping[name]" value="<?php echo $shippings['name'] ?>" />
        </div>

        <div class="eachdiv">
            <label>EDIT AMOUNT</label>
            <input type="number" name="shipping[amount]" value="<?php echo $shippings['amount'] ?>" />
        </div>

        <div class="eachdiv">
            <label>EDIT STATUS</label>
            <select name="shipping[status]">
                <option value="active" <?php if($shippings['status'] == 'active' ){echo "selected";} ?>>Active</option>
                <option value="inactive" <?php if($shippings['status'] == 'inactive'){echo "selected";} ?>>Inactive</option>
            </select>
        </div>

        

        <div class="eachdiv">
            <input type="submit" class="submitbutton" />
            <a href="index.php?c=shipping&a=grid">CANCEL</a>
        </div>
    </div>
</form>
</body>
</html>