<?php
$admins = $this->admins;
?>
<body>
<form action="<?php echo Ccc::getModel('Core_Url')->getUrl('admin' , 'save' , ['id' => $admins->admin_id]) ?>" method="post">
    <div class="mainadd">

        <div class="eachdiv">
            <label>email</label>
            <input type="text" name="admin[email]" value="<?php echo $admins->name ?>" />
        </div>

        <div class="eachdiv">
            <label>pASSwORD</label>
            <input type="number" name="admin[password]" value="<?php echo $admins->password ?>" />
        </div>

        <div class="eachdiv">
            <label>sTATUS</label>
            <select name="admin[status]">
                <option value="active" <?php if($admins->status == 'active' ){echo "selected";} ?>>Active</option>
                <option value="inactive" <?php if($admins->status == 'inactive'){echo "selected";} ?>>Inactive</option>
            </select>
        </div>

        

        <div class="eachdiv">
            <input type="submit" class="submitbutton" />
            <a href="<?php echo Ccc::getModel('Core_Url')->getUrl('admin' , 'grid',[], true) ?>">CANCEL</a>
        </div>
    </div>
</form>
</body>
</html>