<?php
$admins = $this->admins;
// print_r($admins);

?>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="skin/css/grid.css?<?php echo time(); ?>">
    <title>Admin page</title>
</head>
<body>
<div class="maindiv">
        <div class="subdiv">
            <!-- header -->
            <div class="headerr">
                <?php require_once 'view/html/header.phtml'; ?>
            </div>
            <!-- head -->
            <div class="headd">
                <span>Admins</span>
                <a href="<?php echo Ccc::getModel('Core_Url')->getUrl('admin', 'add') ?>">Add Admin</a>
            </div>
        </div>  
        
        <!-- data table -->
        <div class="table">
            <table border="1px" border-collapse= "collapse">
                <tr>
                    <th>Admin ID</th>
                    <th>Email</th>
                    <th>Status</th>
                    <th>Created At</th>
                    <th>Updated At</th>
                    <th colspan="2">
                        OPERATIONS</th>
                </tr>
                    <?php
                    foreach($admins as $admin){
                    ?>
                <tr>
                        <td><?php echo $admin->admin_id; ?></td>
                        <td><?php echo $admin->email; ?></td>
                        <td><?php echo $admin->status; ?></td>
                        <td><?php echo $admin->created_at; ?></td>
                        <td><?php echo $admin->updated_at; ?></td>
                        <td><a href="<?php echo Ccc::getModel('Core_Url')->getUrl('admin', 'edit' , ['id' => $admin->admin_id]) ?>">EDIT</a></td>
                        <td><a href="<?php echo Ccc::getModel('Core_Url')->getUrl('admin', 'delete' , ['id' => $admin->admin_id]) ?>">DELETE </a></td>
                </tr>

                    <?php
                    }
                    ?>
            </table>
        </div>

        <div>
            <?php require_once 'View/html/footer.phtml' ?>
        </div>
    </div>
</body>
</html>