<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Layout</title>
</head>
<body>
<?php 
// echo "<pre>";
// print_r($this); ?>
<table border="1px" border-collapse= "collapse" width="100%">
   
    <tr height=100px align-items="center">
        <td colspan="3">
            <?php $this->getChild('header')->render(); ?>
        </td>
    </tr>
    <tr height=20px>
        <td colspan="3">
            <?php $this->getChild('message')->render(); ?>
        </td>
    </tr>
    <tr height=200px>
        <td>Left</td>
        <!-- <td>Content</td> -->
        <td><?php $this->getChild('content')->render(); ?></td>
        <td>Right</td>
    </tr>
    <tr height=100px>
        <td colspan="3">
            <?php $this->getChild('footer')->render(); ?>
        </td>
    </tr>
</table>
</body>
</html>