<!DOCTYPE html>
<?php 
$this->getChild('head')->render();
?>
<body>

<table border="1px" border-collapse= "collapse" width="100%">
   
    <tr height=100px align-items="center">
        <td colspan="3">
            <?php $this->getChild('header')->render(); ?>
        </td>
    </tr>
    <tr height=20px>
        <td colspan="3">
            <?php $this->getChild('message')->render(); ?>
        </td>
    </tr>
    <tr height=200px>
        <td><?php $this->getChild('left')->render(); ?></td>
        <td><?php $this->getChild('content')->render(); ?></td>
        <td><?php $this->getChild('right')->render(); ?></td>
    </tr>
    <tr height=100px>
        <td colspan="3">
            <?php $this->getChild('footer')->render(); ?>
        </td>
    </tr>
</table>
</body>
</html>