<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="skin/css/add.css?<?php echo time(); ?>" />
    <title>Add data</title>
</head>
<body>
<form method="post" action="<?php echo $this->getUrlObj()->getUrl('customer', 'insert') ?>">
    <div class="mainadd">
        <div class="eachdiv">
            <label>FIRST NAME</label>
            <input type="text" name="customer[first_name]" value="" /> 
        </div>

        <div class="eachdiv">
            <label>LAST NAME</label>
            <input type="text" name="customer[last_name]" value="" /> 
        </div>

        <div class="eachdiv">
            <label>EMAIL</label>
            <input type="email" name="customer[email]" value="" />
        </div>

        <div class="eachdiv">
            <label>GENDER</label>
            <select name="customer[gender]">
                <option value="male">Male</option>
                <option value="female">Female</option>
            </select>
        </div>

        <div class="eachdiv">
            <label>MOBILE NO.</label>
            <input type="tel" name="customer[mobile]" value="" />
        </div>

        <div class="eachdiv">
            <label>STATUS</label>
            <select name="customer[status]">
                <option value="active">Active</option>
                <option value="inactive">inactive</option>
            </select>
        </div>

        <div class="eachdiv">
            <input type="submit" class="submitbutton" />
            <a href="<?php echo $this->getUrlObj()->getUrl('customer', 'grid',[], true) ?>">CANCEL</a>
        </div>
    </div>
</form>
</body>
</html>