<?php
$customers = $this->getCollection()->getData();
?>
<body>
<div class="maindiv">
    <div class="subdiv">
        <div class="headerr">
            <?php require_once 'view/html/header.phtml'; ?>
        </div>
        <div class="headd">
            <span>Customers</span>
            <a href="<?php echo Ccc::getModel('Core_Url')->getUrl('customer', 'add') ?>">Add Customer</a>
        </div>
    </div>  

    <!-- content -->
    <div class="table">
        <table border="1px" border-collapse= "collapse">    
            <tr>
                <th>Customer id</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Gender</th>
                <th>Mobile</th>
                <th>Status</th>
                <th>Created At</th>
                <th>Updated At</th>
                <th>EDIT</th>
                <th>DELETE</th>
            </tr>

            <?php foreach($customers as $customer): ?>    
                <tr>
                    <td><?php echo $customer->customer_id ?></td>
                    <td><?php echo $customer->first_name ?></td>
                    <td><?php echo $customer->last_name ?></td>
                    <td><?php echo $customer->email ?></td>
                    <td><?php echo $customer->gender ?></td>
                    <td><?php echo $customer->mobile ?></td>
                    <td><?php echo $customer->status ?></td>
                    <td><?php echo $customer->created_at ?></td>
                    <td><?php echo $customer->updated_at ?></td>
                    <td><a href="<?php echo Ccc::getModel('Core_Url')->getUrl('customer', 'edit', ['id' => $customer->customer_id]) ?>">EDIT</a></td>
                    <td><a href="<?php echo Ccc::getModel('Core_Url')->getUrl('customer', 'delete', ['id' => $customer->customer_id]) ?>">DELETE</a></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>

        <div>
            <?php require_once 'View/html/footer.phtml' ?>
        </div>    
    </div>
</body>
</html>