<?php
$payments = $this->payments;

// echo "<pre>";
// print_r($payments);
// die;
?>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="skin/css/grid.css?<?php echo time(); ?>">
    <title>payment</title>
</head>
<body>
<div class="maindiv">
        <div class="subdiv">
            <!-- header -->
            <div class="headerr">
                <?php require_once 'view/html/header.phtml'; ?>
            </div>
            <!-- head -->
            <div class="headd">
                <span>payment</span>
                <a href="<?php echo Ccc::getModel('Core_Url')->getUrl('payment' , 'add') ?>">Add payment</a>
            </div>
        </div>  
        
        <!-- data table -->
        <div class="table">
            <table border="1px" border-collapse= "collapse">
                <tr>
                    <th>payment id</th>
                    <th>Name</th>
                    <th>Amount</th>
                    <th>Status</th>
                    <th>Created At</th>
                    <th>Updated At</th>
                    
                    <th>EDIT</th>
                    <th>DELETE</th>
                </tr>
                <?php foreach($payments as $payment): ?>
                    <tr>
                        <td><?php echo $payment->payment_method_id; ?></td>
                        <td><?php echo $payment->name; ?></td>
                        <td><?php echo $payment->amount; ?></td>
                        <td><?php echo $payment->status; ?></td>
                        <td><?php echo $payment->created_at; ?></td>
                        <td><?php echo $payment->updated_at; ?></td>
                        <td><a href="<?php echo Ccc::getModel('Core_Url')->getUrl('payment', 'edit', ['id' => $payment->payment_method_id ]) ?>">EDIT</a></td>
                        <td><a href="<?php echo Ccc::getModel('Core_Url')->getUrl('payment', 'delete', ['id' => $payment->payment_method_id ]) ?>">DELETE</a></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>

        <div>
            <?php require_once 'View/html/footer.phtml' ?>
        </div>
    </div>
</body>
</html>