<?php
$payments = $this->payments;

// echo "<pre>";
// print_r($payments);
// die;
?>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="skin/css/grid.css?<?php echo time(); ?>">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script> -->
    <title>payment</title>
</head>
<body>
<div class="maindiv">
        <div class="subdiv">
            <!-- header -->
            <div class="headerr">
                <!-- <?php require_once 'view/html/header.phtml'; ?> -->
            </div>
            <!-- head -->
            <div class="headd">
                <span>payment</span>
                <a class="link-success" href="<?php echo Ccc::getModel('Core_Url')->getUrl('payment' , 'add') ?>">Add payment</a>
            </div>
        </div>  
        
        <!-- data table -->
        <div class="table">
            <table class="table" border="1px" border-collapse= "collapse" >
                <tr>
                    <th>payment id</th>
                    <th>Name</th>
                    <th>Amount</th>
                    <th>Status</th>
                    <th>Created At</th>
                    <th>Updated At</th>
                    
                    <th>EDIT</th>
                    <th>DELETE</th>
                </tr>
                <?php if(!$payments): ?>
                    <tr><td colspan="8">no data available</td></tr>
                
                <?php else: ?>
                <?php foreach($payments as $payment): ?>
                    <tr>
                        <td><?php echo $payment->payment_method_id; ?></td>
                        <td><?php echo $payment->name; ?></td>
                        <td><?php echo $payment->amount; ?></td>
                        <td><?php echo $payment->status; ?></td>
                        <td><?php echo $payment->created_at; ?></td>
                        <td><?php echo $payment->updated_at; ?></td>
                        <td><a class="link-primary" href="<?php echo Ccc::getModel('Core_Url')->getUrl('payment', 'edit', ['id' => $payment->payment_method_id ]) ?>">EDIT</a></td>
                        <td><a class="link-danger" href="<?php echo Ccc::getModel('Core_Url')->getUrl('payment', 'delete', ['id' => $payment->payment_method_id ]) ?>">DELETE</a></td>
                    </tr>
                <?php endforeach; ?>
                <?php endif; ?>
            </table>
        <!-- </div> -->

        <div>
            <!-- <?php require_once 'View/html/footer.phtml' ?> -->
        </div>
        </div>
    </div>
</body>
</html>