<?php
$categories = $this->category;
print_r($categories);
// die;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="skin/css/grid.css?<?php echo time(); ?>">
    <title>Category</title>
</head>
<body>
<div class="maindiv">
    <div class="subdiv">
            <!-- header -->
            <div class="headerr">
                <?php require_once 'view/html/header.phtml'; ?>
            </div>
            <!-- head -->
            <div class="headd">
                <span>Category</span>
                <a href="<?php echo Ccc::getModel("Core_Url")->getUrl('category' , 'add') ?>">Add product</a>
            </div>
        </div>
</div>
</body>
</html>