<?php
$categories = $this->getCategory();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="skin/css/grid.css?<?php echo time(); ?>">
    <title>Category</title>
</head>
<body>
<div class="maindiv">
        <div class="subdiv">
            <!-- header -->
            <div class="headerr">
                <?php require_once 'view/html/header.phtml'; ?>
            </div>
            <!-- head -->
            <div class="headd">
                <span>Category</span>
                <!-- <a href="index.php?c=category&a=add">Add Category</a> -->
                <a href="<?php echo $this->getUrlObj()->getUrl('category', 'add') ?>">Add Category</a>
            </div>
        </div>  
        
        <!-- data table -->
        <div class="table">
            <table border="1px" border-collapse= "collapse">
                <tr>
                    <th>Category id</th>
                    <th>Name</th>
                    <th>Status</th>
                    <th>Description</th>
                    <th>Created At</th>
                    <th>Updated At</th>
                    <th>EDIT</th>
                    <th>DELETE</th>
                </tr>
                <?php foreach($categories as $category): ?>
                    <tr>
                        <td><?php echo $category['category_id'] ?></td>
                        <td><?php echo $category['name'] ?></td>
                        <td><?php echo $category['status'] ?></td>
                        <td><?php echo $category['description'] ?></td>
                        <td><?php echo $category['created_at'] ?></td>
                        <td><?php echo $category['updated_at'] ?></td>
                        <td><a href="<?php echo $this->getUrlObj()->getUrl('category', 'edit' , ['id' => $category['category_id']]); ?>">EDIT</a></td>

                        <td><a href="<?php echo $this->getUrlObj()->getUrl('category', 'delete', ['id' => $category['category_id']]); ?>">DELETE</a></td>

                    </tr>
                <?php endforeach; ?>
            </table>
        </div>

        <div>
            <?php require_once 'View/html/footer.phtml' ?>
        </div>
    </div>
</body>
</html>