<?php
$salesmans = $this->getSalesMan();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="skin/css/edit.css?<?php echo time(); ?>">
    <title>Edit data</title>
</head>
<body>
<form method="post" action="<?php echo $this->getUrlObj()->getUrl('salesman' , 'update' , ['id' => $salesmans['salesman_id']]) ?>">
    <div class="mainadd">
        <div class="eachdiv">
            <label>FIRST NAME</label>
            <input type="text"  name="salesman[first_name]" value="<?php echo $salesmans['first_name'] ?>" />
        </div>

        <div class="eachdiv">
            <label>LAST NAME</label>
            <input type="text"  name="salesman[last_name]" value="<?php echo $salesmans['last_name'] ?>" />
        </div>

        <div class="eachdiv">
            <label> EMAIL</label>
            <input type="email"  name="salesman[email]" value="<?php echo $salesmans['email'] ?>" />
        </div>

        <div class="eachdiv">
            <label>GENDER</label>
            <select name="salesman[gender]">
                <option value="male <?php if($salesmans['gender'] == 'male') {echo 'selected';} ?>">Male</option>
                <option value="female <?php if($salesmans['gender'] == 'female'){echo 'selected';} ?>">Female</option>
            </select>
        </div>

        <div class="eachdiv">
            <label>MOBILE</label>
            <input type="tel"  name="salesman[mobile]" value="<?php echo $salesmans['mobile'] ?>" />
        </div>

        <div class="eachdiv">
            <label>STATUS</label>
            <select name="salesman[status]">
                <option value="active <?php if($salesmans['status'] == 'active'){echo 'selected';} ?>">Active</option>
                <option value="inactive <?php if($salesmans['status'] == 'inactive'){echo 'selected';} ?>">Inactive</option>
            </select>
        </div>

        <div class="eachdiv">
            <label>COMPANY</label>
            <input type="text"  name="salesman[company]" value="<?php echo $salesmans['company'] ?>" />
        </div>

        <div class="eachdiv">
            <input type="submit" class="submitbutton" />
            <a href="<?php echo $this->getUrlObj()->getUrl('salesman', 'grid',[], true) ?>">CANCEL</a>
        </div>
    </div>
</form>
</body>
</html>